FROM nginx:1.17.0
LABEL maintainer Peiyu

COPY ./deploy/nginx.conf /etc/nginx/nginx.conf

CMD envsubst '\$NGINX_PORT, \$NGINX_PROJECT, \$NGINX_UWSGI_INTERNAL_PORT'  < /nginx.conf.template > /etc/nginx/nginx.conf && \
    exec nginx -g "daemon off;"